name: Test

on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  Test:
    name: Run tests and checkers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Run tests
        run: |
          go test

      - name: Run go vet
        run: |
          go vet -mod=readonly  . ./cmd

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck . ./cmd

      - name: Run errcheck
        run: |
          go install github.com/kisielk/errcheck@latest
          errcheck . ./cmd

  Lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
